Repository MicrosoftDocs/microsoft-365-docs, pull requests merged in 2024-07, with the labels that each got.

#13587 Create workflow
  .github/workflows/Shared-AutoLabelAssign.yml
Labels: Microsoft submitter

#13589 add pull_request_target event
  .github/workflows/Shared-AutoLabelAssign.yml
Labels: Microsoft submitter

#13579 Update loop-components-teams.md
  microsoft-365/loop/loop-components-teams.md
Labels: Microsoft submitter, loop/svc

#13590 Update flw-devices.md
  microsoft-365/frontline/flw-devices.md
Labels: microsoft-365-frontline/svc

#13591 Create Shared-ProtectedFiles.yml
  .github/workflows/Shared-ProtectedFiles.yml
Labels: Microsoft submitter

#13594 add pr file count messages
  .github/workflows/resources/PrFileCountCheck-PrivateBlockMessage.md
  .github/workflows/resources/PrFileCountCheck-PrivateWarningMessage.md
  .github/workflows/resources/PrFileCountCheck-PublicBlockMessage.md
  .github/workflows/resources/PrFileCountCheck-PublicWarningMessage.md
Labels: Microsoft submitter

#13595 Add pr file count workflow and support protected file check pagination
  .github/workflows/Shared-PrFileCount.yml
  .github/workflows/Shared-ProtectedFiles.yml
Labels: Microsoft submitter

#13596 Update esignature-overview.md
  microsoft-365/syntex/esignature-overview.md
Labels: microsoft-syntex/svc, syntex-content-intelligence/subsvc

#13597 Create LiveMergeCheck-LiveMergeMessage.md
  .github/workflows/resources/LiveMergeCheck-LiveMergeMessage.md
Labels: Microsoft submitter

#13607 Update esignature-setup.md
  microsoft-365/syntex/esignature-setup.md
Labels: Microsoft submitter, microsoft-syntex/svc, syntex-content-intelligence/subsvc
